<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-Pabloacostatec-A01794035-/blob/main/Semana_3_Python_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Semana 3: Python for Data Science**

Alumno: Juan Pablo Acosta

Matrícula : A01794035

Materia Ciencia y analítica de datos

Profesor titular: Jobish Vallikavungal Devassia

Profesor tutor: Victoria Guerrero Orozco

Fecha 02/10/2023

#Sección 1: trabajando con arreglos de numpy

Los arreglos de numpy son matrices de un sólo tipo de valor que pueden ser transformadas, además los arreglos de numpy ya tienen funciones incluidas como suma, resta multiplicación y división de vectores.

la función que se utiliza para declarar un arreglo es: np.array

#Ejercicios de Lab de arreglos de numpy

In [91]:
import numpy as np

In [92]:
#Implement the following vector subtraction in numpy: u-v

u = np.array([1, 0])
v = np.array([0, 1])

Subs = u-v

np.array(Subs)

# Multiply the array *2

z = np.array([2, 4])
Mult = z*2

np.array(Mult)

#Consider the list [1, 2, 3, 4, 5] and [1, 0, 1, 0, 1]. Cast both lists to a numpy array then multiply them together:

l1 = np.array([1,2,3,4,5])
l2 = np.array([1,0,1,0,1])

MultArray = l1*l2
MultArray

array([1, 0, 3, 0, 5])

In [93]:
from ssl import VerifyMode
import time 
import sys


import matplotlib.pyplot as plt
%matplotlib inline  

def Plotvec2(a,b):
    ax = plt.axes()# to generate the full window axes
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)#Add an arrow to the  a Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)#Add an arrow to the  b Axes with arrow head width 0.05, color blue and arrow head length 0.1
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)

#Convert the list [-1, 1] and [1, 1] to numpy arrays a and b. Then, plot the arrays as vectors using the fuction Plotvec2 and find their dot product:

u = np.array([-1, 1])
v = np.array([1, 1])

#Plotvec2(u,v)

#Convert the list [1, 0] and [0, 1] to numpy arrays a and b. Then, plot the arrays as vectors using the function Plotvec2 and find their dot product:

u = np.array([1, 0])
v = np.array([0, 1])

dot = np.dot(u,v)
#Plotvec2(u,v)
print(dot)

#Convert the list [1, 1] and [0, 1] to numpy arrays a and b. Then plot the arrays as vectors using the fuction Plotvec2 and find their dot product:

u = np.array([1, 1])
v = np.array([0, 1])

dot = np.dot(u,v)
#Plotvec2(u,v)
print(dot)

#Why are the results of the dot product for [-1, 1] and [1, 1] and the dot product for [1, 0] and [0, 1] zero, but not zero for the dot product for [1, 1] and [0, 1]? 

#Vectorial dot products is basically the cast of one vector into the other, the first two vector cannot cast into the others and the third, can.

#Convert the list [1, 2, 3] and [8, 9, 10] to numpy arrays arr1 and arr2. Then perform Addition , Subtraction , Multiplication , Division and Dot Operation on the arr1 and arr2.

u = np.array([1,2,3])
v = np.array([8,9,10])

Addi = u+v
Subs = u-v
Mult = u*v
Divi = u/v
DotOper = np.dot(u,v)

#Convert the list [1, 2, 3, 4, 5] and [6, 7, 8, 9, 10] to numpy arrays arr1 and arr2. Then find the even and odd numbers from arr1 and arr2.

u = np.array([1,2,3,4,5])
v = np.array([6,7,8,9,10])

x = u[1:8:2]
x
   
y = v[0:8:2]
y  

x = u[1:8:1]
x
   
y = v[1:8:2]
y  


0
1


array([7, 9])

##Ejercicios de Lab, arreglos multidimensionales

In [94]:
#Consider the following list a, convert it to Numpy Array.

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Array = np.array(a)

#Calculate the numpy array size.

Array.size

#Access the element on the first row and first and second columns.

Array[:,0:2]
#Perform matrix multiplication with the numpy arrays A and B.

b = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

Mult = np.dot(a,b)
Mult

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

#Sección API's

API's son protocolos de llamado entre dos piezas de software, comunmente utilizadas para utilizar los distintos servicios web, existen varios tipos de APIs

REST

SOAP

JSON

...
ETC



##Laboratorio de APIs

En esta sección se van a hacer ejercicios para obtener información de un sitio web con el método "GET", en este caso el servicio web es un servicio de prueba proveído por IBM.com

In [95]:
import requests
import os 
from PIL import Image
from IPython.display import IFrame

In [96]:
url='https://www.ibm.com/'
r=requests.get(url)
r
header=r.headers
#print(r.headers)
print(r.request.headers)
header['date']
header['Content-Type']
r.text[0:100]
r=requests.get(url)

{'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '_abck=3503F9986AAE8B25A466619967B32AB7~-1~YAAQtQNAFxujVlmDAQAAAj/TmQgB27+JjDNp/FTiS1mUQt/UXWl7OsHKjYDndAlatIepsbrykr/yf/PM6FLfzH6SqNMyCS+p3pAhZ589Ehxr+tMIP+OtsjrkfUjloNHy4cO/9loHIaTOt99/NJGlKRIjzumFa8ky4dsFlaMdDkOVckt2TpAbtoSahYvfK2hgQukgT5FFHLyQNWwKsNg1NEEH+pg3CMR0ZYSY6Uvm1WOOmyMjQ+SE8htzuKMnRYl/P7AcUKn8h3/OLLeeI6rO08PRBM/PBEPpqLbNcl9bOkkjyHWiZaswAwfNczLdWpvx3MBo3SxpprKLzmuOjm3MnS2E0k96PwVD/HfcuEEGH5FhhXd+t70=~-1~-1~-1; bm_sz=E51AD47E7F56A6A29904630A5182A842~YAAQtQNAFxyjVlmDAQAAAj/TmREinATuzB3oi57keBf3h/VRUB3X8sny4aytVaYnK5U9iXtirbkZo1xMP5KDrfohL1r1bRiNtNEJE7Z16KPH13+deAUU5h5T91pacqj9XmfEVd+qiQt9zYv1KwrtDDksftGHgVA84PMN40Chb82wWNkgVDqkVRQAFsbmOPtJjS/eyecvnzmE6SMLMW4MoH9YU5w96mmP6kq6Wju8dPAAhgivAhRCIUuhBjYmt3eGI9QfrmEmb9/9IhlyAf44wuL97IIMHXooRqK+de0/7J0=~4277558~4403265'}


In [97]:
url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Example1.txt'
path=os.path.join(os.getcwd(),'Example.txt')
r=requests.get(url)
with open(path,'wb') as f:
    f.write(r.content)
r,header


(<Response [200]>,
 {'Server': 'Apache', 'Last-Modified': 'Mon, 26 Sep 2022 12:10:36 GMT', 'ETag': '"182c6-5e9936a544ba1-gzip"', 'Accept-Ranges': 'bytes', 'Content-Encoding': 'gzip', 'Content-Type': 'text/html', 'Cache-Control': 'max-age=3600', 'Expires': 'Sun, 02 Oct 2022 18:51:41 GMT', 'X-Akamai-Transformed': '9 21429 0 pmb=mTOE,2', 'Date': 'Sun, 02 Oct 2022 17:51:41 GMT', 'Content-Length': '21615', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'x-content-type-options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': 'upgrade-insecure-requests', 'Strict-Transport-Security': 'max-age=31536000'})

In [98]:
url_get='http://httpbin.org/get'
payload={"name":"Joseph","ID":"123"}
r=requests.get(url_get,params=payload)
r.url
print("request body:", r.request.body)
print(r.status_code)
print(r.text)
r.headers['Content-Type']
r.json()
r.json()['args']

request body: None
200
{
  "args": {
    "ID": "123", 
    "name": "Joseph"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.23.0", 
    "X-Amzn-Trace-Id": "Root=1-6339cfae-5c4ca9f45855aac52b62459d"
  }, 
  "origin": "34.83.9.237", 
  "url": "http://httpbin.org/get?name=Joseph&ID=123"
}



{'ID': '123', 'name': 'Joseph'}

In [99]:
url_post='http://httpbin.org/post'
r_post=requests.post(url_post,data=payload)
print("POST request URL:",r_post.url )
print("GET request URL:",r.url)
print("POST request body:",r_post.request.body)
print("GET request body:",r.request.body)
print("POST request body:",r_post.request.body)
print("GET request body:",r.request.body)

POST request URL: http://httpbin.org/post
GET request URL: http://httpbin.org/get?name=Joseph&ID=123
POST request body: name=Joseph&ID=123
GET request body: None
POST request body: name=Joseph&ID=123
GET request body: None
